# Generated by Django 6.0.1 on 2026-01-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key',
            field=models.CharField(default=None, help_text='Project key like JIRA, TMS', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('organization', 'key')},
        ),
    ]
