# Generated by Django 6.0.1 on 2026-01-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={},
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='is_active',
        ),
        migrations.AddField(
            model_name='sprint',
            name='goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
